### PR TITLE
Disasm using capstone

### PR DESCRIPTION
**Pull request by david942j**
Support i386 and amd64

<del>base on #18 
[diff with #18 ](https://github.com/peter50216/pwntools-ruby/compare/feature/shellcraft_i386...feature/disasm)</del>

TODO:
1. ~~Nice error message should be present if capstone is not installed yet
currently the following message will be shown when `require 'pwn'`:~~
```
Could not open library 'capstone': capstone: cannot open shared object file: No such file or directory.
Could not open library 'libcapstone.so': libcapstone.so: cannot open shared object file: No such file or directory.
Could not open library 'libcapstone.so.3': libcapstone.so.3: cannot open shared object file: No such file or directory
```
2. Handle when input is invalid (currently will raise `Crabstone::ErrOK: OK (CS_ERR_OK)`)

---
This change is [Reviewable](https://reviewable.io/reviews/peter50216/pwntools-ruby/20)

### CODE REVIEW

**Comment by hanhanW** [comment]
There are some conflicts, please fix it.

**Comment by hanhanW** [comment]
Reviewed 5 of 63 files at r3, 2 of 9 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Gemfile, line 5 at r4](https://reviewable.io:443/reviews/peter50216/pwntools-ruby/20#-KsXPRosHvQiyOkK7hOO:-KsXPRosHvQiyOkK7hOP:bo63r15) ([raw file](https://github.com/peter50216/pwntools-ruby/blob/d58a471d33fcf108764c36170ee97f86e166e911/Gemfile#L5)):*
> ```Ruby
> gemspec
> 
> gem 'crabstone', git: 'https://github.com/bnagy/crabstone' # it doesn't push to RubyGems :(
> ```

Request `crabstone` for publishing the gem.

---

*[lib/pwnlib/asm.rb, line 28 at r4](https://reviewable.io:443/reviews/peter50216/pwntools-ruby/20#-KsXQqy50tfcuuy5_dAo:-KsXQqy50tfcuuy5_dAp:bj3f1sv) ([raw file](https://github.com/peter50216/pwntools-ruby/blob/d58a471d33fcf108764c36170ee97f86e166e911/lib/pwnlib/asm.rb#L28)):*
> print disasm("\xb8\x5d\x00\x00")
print disasm("\xb8\x5d\x00\x00\x00")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/peter50216/pwntools-ruby/20)*

**Comment by hanhanW** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/pwnlib/asm.rb, line 54 at r4](https://reviewable.io:443/reviews/peter50216/pwntools-ruby/20#-KsXh6OXkQ3sPT5Ptkkn:-KsXh6OXkQ3sPT5Ptkko:bpccfun) ([raw file](https://github.com/peter50216/pwntools-ruby/blob/d58a471d33fcf108764c36170ee97f86e166e911/lib/pwnlib/asm.rb#L54)):*
> ```Ruby
>       insts.reduce('') do |s, ins|
>         hex_code = ins[1].bytes.map { |c| format('%02x', c) }.join(' ')
>         inst = if ins[3].empty?
> ```

newline after `=` or use ternary operator

https://github.com/bbatsov/ruby-style-guide#use-if-case-returns

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/peter50216/pwntools-ruby/20)*

**Comment by david942j** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[Gemfile, line 5 at r4](https://reviewable.io:443/reviews/peter50216/pwntools-ruby/20#-KsXPRosHvQiyOkK7hOO:-KsXrDu05ixtz8CKcrNz:b-896fix) ([raw file](https://github.com/peter50216/pwntools-ruby/blob/d58a471d33fcf108764c36170ee97f86e166e911/Gemfile#L5)):*
<details><summary><i>Previously, hanhanW wrote…</i></summary><blockquote>

Request `crabstone` for publishing the gem.
</blockquote></details>

Done.

---

*[lib/pwnlib/asm.rb, line 28 at r4](https://reviewable.io:443/reviews/peter50216/pwntools-ruby/20#-KsXQqy50tfcuuy5_dAo:-KsXv7xZPt3F6QKb9AMW:b-896fix) ([raw file](https://github.com/peter50216/pwntools-ruby/blob/d58a471d33fcf108764c36170ee97f86e166e911/lib/pwnlib/asm.rb#L28)):*
<details><summary><i>Previously, hanhanW wrote…</i></summary><blockquote>

> print disasm("\xb8\x5d\x00\x00")
print disasm("\xb8\x5d\x00\x00\x00")
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/peter50216/pwntools-ruby/20)*

**Comment by hanhanW** [comment]
LGTM
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/peter50216/pwntools-ruby/20#-:-KsYQ3Vy23QGcCGg46jv:b3hosot)*

**Pull request merged**
